"""Database initialization

Revision ID: b4a06157f4ef
Revises: 
Create Date: 2017-12-28 22:05:00.498670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a06157f4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('symbol')
    )
    op.create_table('effect',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('gene_id', sa.Integer(), nullable=True),
        sa.Column('effect_type', sa.Enum('prime3_utr', 'prime3_utr_intron', 'prime5_utr', 'prime5_utr_intron', 'cds', 'cnv_plus', 'cnv_minus', 'frame_shift', 'intergenic', 'intron', 'missense', 'no_frame_shift', 'no_frame_shift_new_stop', 'no_end', 'no_start', 'non_coding', 'non_coding_intron', 'nonsense', 'splice_site', 'synonymous', name='effecttype'), nullable=False),
        sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variant', sa.String(length=64), nullable=False),
        sa.Column('variant_type', sa.Enum('substitution', 'deletion', 'insertion', 'cnv', 'complex', name='varianttype'), nullable=False),
        sa.Column('chromosome', sa.String(length=2), nullable=False),
        sa.Column('location', sa.Integer(), nullable=False),
        sa.Column('worst_effect_id', sa.Integer(), nullable=True),
        sa.Column('n_par_called', sa.Integer(), nullable=True),
        sa.Column('n_alt_alls', sa.Integer(), nullable=True),
        sa.Column('prcnt_par_called', sa.Float(), nullable=True),
        sa.Column('alt_freq', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['worst_effect_id'], ['effect.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chromosome', 'location', 'variant_type', 'variant', name='chr_loc_var_uidx')
    )
    op.create_foreign_key('fk_effect_variant', 'effect', 'variant', ['variant_id'], ['id'])
    op.create_table('numeric_attribute',
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Enum('e65_freq', 'evs_freq', 'ssc_freq', name='attributename'), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
        sa.PrimaryKeyConstraint('variant_id', 'name')
    )
    op.create_index('name_value_idx', 'numeric_attribute', ['name', 'value'], unique=False)
    op.create_table('family',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('family_ext_id', sa.Integer(), nullable=True),
        sa.Column('kids_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('family_ext_id')
    )
    op.create_table('person',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('gender', sa.Enum('female', 'male', 'unknown', name='gender'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_member',
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('order_in_family', sa.Integer(), nullable=False),
        sa.Column('role_in_family', sa.Enum('paternal_grandfather', 'paternal_grandmother', 'maternal_grandfather', 'maternal_grandmother', 'unknown', 'parent', 'spouse', 'mom', 'maternal_uncle', 'maternal_aunt', 'step_dad', 'maternal_cousin', 'dad', 'paternal_uncle', 'paternal_aunt', 'step_mom', 'paternal_cousin', 'prb', 'sib', 'maternal_half_sibling', 'paternal_half_sibling', 'child', name='familyrole'), nullable=False),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
        sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
        sa.PrimaryKeyConstraint('family_id', 'person_id')
    )
    op.create_table('family_variant',
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('present_in_affected', sa.Boolean(), nullable=False),
        sa.Column('present_in_unaffected', sa.Boolean(), nullable=False),
        sa.Column('present_in_mom', sa.Boolean(), nullable=False),
        sa.Column('present_in_dad', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
        sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
        sa.PrimaryKeyConstraint('variant_id', 'family_id')
    )
    op.create_table('person_variant',
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('alt_allele_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
        sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
        sa.PrimaryKeyConstraint('variant_id', 'person_id')
    )
    op.create_index(op.f('ix_variant_alt_freq'), 'variant', ['alt_freq'], unique=False)
    op.create_index(op.f('ix_variant_n_alt_alls'), 'variant', ['n_alt_alls'], unique=False)
    op.create_index(op.f('ix_variant_n_par_called'), 'variant', ['n_par_called'], unique=False)
    op.create_index(op.f('ix_variant_prcnt_par_called'), 'variant', ['prcnt_par_called'], unique=False)
    op.create_index(op.f('ix_variant_variant_type'), 'variant', ['variant_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_variant_type'), table_name='variant')
    op.drop_index(op.f('ix_variant_prcnt_par_called'), table_name='variant')
    op.drop_index(op.f('ix_variant_n_par_called'), table_name='variant')
    op.drop_index(op.f('ix_variant_n_alt_alls'), table_name='variant')
    op.drop_index(op.f('ix_variant_alt_freq'), table_name='variant')
    op.drop_table('person_variant')
    op.drop_table('family_variant')
    op.drop_table('family_member')
    op.drop_table('person')
    op.drop_table('family')
    op.drop_index('name_value_idx', table_name='numeric_attribute')
    op.drop_table('numeric_attribute')
    op.drop_constraint('fk_effect_variant', 'effect', type_='foreignkey')
    op.drop_table('variant')
    op.drop_table('effect')
    op.drop_table('gene')
    # ### end Alembic commands ###
