FORMAT: 1A

# Genotypes and Phenotypes in Families (GPF) API

## Group Dataset Configurations

### Datasets [/dataset]

#### Get All Datasets [GET]
Returns all supported datasets

+ Response 200 (application/json)

          {
              "data": [
                {
                  "id": "VIP",
                  "name": "VIP Dataset",
                  "studies": "VIP-JHC",
                  "studyTypes": "WE",
                  "phenoDB": "vip",

                  "genotypeBrowser": true,
                  "phenotypeGenotypeTool": true,
                  "enrichmentTool": false,
                  "phenotypeBrowser": true,
                  "commonReport": true,

                  "genotypeBrowserConfig": {
                      "hasCNV": false,
                      "hasAdvancedFamilyFilters": false,
                      "hasPedigreeSelector": true,
                      "hasStudyTypes": false,
                  },
                  "peopleGroups": [
                      {
                          "id": "16pstatus",
                          "name": "16p Status",
                          "source": "phenoDB.pheno_common.genetic_status_16p",
                          "defaultValue": {
                              "color": "#aaaaaa",
                              "id": "unknown",
                              "name": "unknown"
                          },
                          "domain": [
                              {
                                  "color": "#e35252",
                                  "id": "deletion",
                                  "name": "deletion"
                              },
                              {
                                  "color": "#b8008a",
                                  "id": "duplication",
                                  "name": "duplication"
                              },
                              {
                                  "color": "#e3d252",
                                  "id": "triplication",
                                  "name": "triplication"
                              },
                              {
                                  "color": "#ffffff",
                                  "id": "negative",
                                  "name": "negative"
                              }
                          ]
                      },
                      {
                          "id": "phenotypes",
                          "name": "Phenotypes",
                          "source": "legacy",
                          "defaultValue": {
                              "color": "#aaaaaa",
                              "id": "unknown",
                              "name": "unknown"
                          },
                          "domain": [
                              {
                                  "color": "#e35252",
                                  "id": "autism",
                                  "name": "autism"
                              },
                              {
                                  "color": "#ffffff",
                                  "id": "unaffected",
                                  "name": "unaffected"
                              }
                          ]
                      }
                  ]
                }
              ]
            }


### Dateset Details [/dataset/{dataset_id}]
#### Get Dataset Details [GET]
Returns dataset details given `dataset_id`.
+ Parameters
  + dataset_id (string) - ID of a dataset returned by `/dataset` endpoint.

+ Response 200 (application/json)

        {
            "data":
              {
                "id": "VIP",
                "name": "VIP Dataset",
                "studies": "VIP-JHC",
                "studyTypes": "WE",
                "phenoDB": "vip",

                "genotypeBrowser": true,
                "phenotypeGenotypeTool": true,
                "enrichmentTool": false,
                "phenotypeBrowser": true,
                "commonReport": true,

                "genotypeBrowserConfig": {
                    "hasCNV": false,
                    "hasAdvancedFamilyFilters": false,
                    "hasPedigreeSelector": true,
                    "hasStudyTypes": false,
                },
                "peopleGroups": [
                    {
                        "id": "16pstatus",
                        "name": "16p Status",
                        "source": "phenoDB.pheno_common.genetic_status_16p",
                        "defaultValue": {
                            "color": "#aaaaaa",
                            "id": "unknown",
                            "name": "unknown"
                        },
                        "domain": [
                            {
                                "color": "#e35252",
                                "id": "deletion",
                                "name": "deletion"
                            },
                            {
                                "color": "#b8008a",
                                "id": "duplication",
                                "name": "duplication"
                            },
                            {
                                "color": "#e3d252",
                                "id": "triplication",
                                "name": "triplication"
                            },
                            {
                                "color": "#ffffff",
                                "id": "negative",
                                "name": "negative"
                            }
                        ]
                    },
                    {
                        "id": "phenotypes",
                        "name": "Phenotypes",
                        "source": "legacy",
                        "defaultValue": {
                            "color": "#aaaaaa",
                            "id": "unknown",
                            "name": "unknown"
                        },
                        "domain": [
                            {
                                "color": "#e35252",
                                "id": "autism",
                                "name": "autism"
                            },
                            {
                                "color": "#ffffff",
                                "id": "unaffected",
                                "name": "unaffected"
                            }
                        ]
                    }
                ]
            }
        }

+ Response 404 (application/json)

          {
            "reason": "Dataset 'dataset_id' not found"
          }

### Dataset Phenotypes [/dataset/{dataset_id}/phenotypes]
#### Get Dataset Phenotypes [GET]
Returns all phenotypes in given dataset.
+ Parameters
  + dataset_id (string) - ID of a dataset returned by `/dataset` endpoint.

+ Response 200 (application/json)

          {
            "data":
              [
                {
                  "id": "autism",
                  "description": "autism",
                  "color": "#e35252"
                },
                {
                  "id": "congenital_heart_disease",
                  "description": "congenital heart disease",
                  "color": "#b8008a"
                },
                {
                  "id": "epilepsy",
                  "description": "epilepsy",
                  "color": "#e3d252"
                },
                {
                  "id": "intelectual_disability",
                  "description": "intelectual disability",
                  "color": "#99d8e8"
                },
                {
                  "id": "schizophrenia",
                  "description": "schizophrenia",
                  "color": "#98e352"
                },
                {
                  "id": "unaffected",
                  "description": "unaffected",
                  "color": "#ffffff"
                }
              ]
          }

+ Response 404 (application/json)

          {
            "reason": "Dataset 'dataset_id' not found"
          }

### Dataset Study Types [/dataset/{dataset_id}/studytypes]
#### Get Dataset Study Types [GET]
Returns all study types in given dataset.
+ Parameters
  + dataset_id (string) - ID of a dataset returned by `/dataset` endpoint.

+ Response 200 (application/json)

          {
            "data":
              [
                {
                  "id": "WE",
                  "description": "Whole Exome"
                },
                {
                  "id": "TG",
                  "description": "Targeted Genome"
                },
                {
                  "id": "WG",
                  "description": "Whole Genome"
                }
              ]
          }

+ Response 404 (application/json)

          {
            "error": "Dataset 'dataset_id' not found"
          }




### Get Whole Genome data for Given Filters [/we_query_variants_preview]

#### Get table data for given filters [POST]
Returns all effect types groups for givent dataset.
+ Request (application/json)
    + Body
          {}

+ Response 200 (application/json)

          {
             "count":"34",
             "rows":[
                [
                   "TUPH",
                   "StromWE2012",
                   "intelectual disability",
                   "2:165381589",
                   "sub(C->A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "splice-site",
                   "GRB14",
                   "",
                   "GRB14:splice-site",
                   "GRB14:splice-site",
                   "denovo",
                   "splice-site",
                   "202/541",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "MS111684",
                   "StromWE2012",
                   "intelectual disability",
                   "2:166172101",
                   "ins(A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "SCN2A",
                   "",
                   "SCN2A:frame-shift",
                   "SCN2A:frame-shift",
                   "denovo",
                   "frame-shift",
                   "502/2006;502/2006;502/2006",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"} ,{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "ER8490",
                   "StromWE2012",
                   "intelectual disability",
                   "2:166179821",
                   "del(2)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "SCN2A",
                   "",
                   "SCN2A:frame-shift",
                   "SCN2A:frame-shift",
                   "denovo",
                   "frame-shift",
                   "609/2006;609/2006;609/2006",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "ER14209",
                   "StromWE2012",
                   "intelectual disability",
                   "3:9490270",
                   "sub(C->T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "SETD5",
                   "",
                   "SETD5:nonsense",
                   "SETD5:nonsense",
                   "denovo",
                   "nonsense",
                   "768/1443(Arg->End)",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "ZH50743",
                   "StromWE2012",
                   "intelectual disability",
                   "3:11060365",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "SLC6A1",
                   "",
                   "SLC6A1:frame-shift|SLC6A1-AS1:non-coding-intron",
                   "SLC6A1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "151/600|1/2[441]",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}, {"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "SB111617",
                   "StromWE2012",
                   "intelectual disability",
                   "5:56174913",
                   "del(4)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "MAP3K1",
                   "",
                   "MAP3K1:frame-shift",
                   "MAP3K1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "691/1513",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "TUTLN",
                   "StromWE2012",
                   "intelectual disability",
                   "5:77437007",
                   "sub(A->C)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "AP3B1",
                   "",
                   "AP3B1:nonsense",
                   "AP3B1:nonsense",
                   "denovo",
                   "nonsense",
                   "488/1046(Leu->End);537/1095(Leu->End)",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "ER53899",
                   "StromWE2012",
                   "intelectual disability",
                   "6:33405934",
                   "del(2)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "SYNGAP1",
                   "",
                   "SYNGAP1:frame-shift",
                   "SYNGAP1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "418/1344",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "BO14/09",
                   "StromWE2012",
                   "intelectual disability",
                   "6:33410959",
                   "ins(T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "SYNGAP1",
                   "",
                   "SYNGAP1:frame-shift",
                   "SYNGAP1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "877/1344",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "NS0908",
                   "StromWE2012",
                   "intelectual disability",
                   "6:86324828",
                   "ins(G)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "SYNCRIP",
                   "",
                   "SYNCRIP:frame-shift",
                   "SYNCRIP:frame-shift",
                   "denovo",
                   "frame-shift",
                   "471/589;506/624;506/562;506/563;408/465;354/411;471/528",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "BO63/11",
                   "StromWE2012",
                   "intelectual disability",
                   "6:143081688",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "HIVEP2",
                   "",
                   "HIVEP2:frame-shift",
                   "HIVEP2:frame-shift",
                   "denovo",
                   "frame-shift",
                   "1913/2447",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "MR-NET001",
                   "StromWE2012",
                   "intelectual disability",
                   "9:130422308",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "splice-site",
                   "STXBP1",
                   "",
                   "STXBP1:splice-site",
                   "STXBP1:splice-site",
                   "denovo",
                   "splice-site",
                   "82/595;82/604",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "BE2407",
                   "StromWE2012",
                   "intelectual disability",
                   "12:51281044",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "splice-site",
                   "TMPRSS12",
                   "",
                   "TMPRSS12:splice-site",
                   "TMPRSS12:splice-site",
                   "denovo",
                   "splice-site",
                   "265/349",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "ER51232",
                   "StromWE2012",
                   "intelectual disability",
                   "13:50057691",
                   "ins(A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "SETDB2",
                   "",
                   "SETDB2:frame-shift",
                   "SETDB2:frame-shift",
                   "denovo",
                   "frame-shift",
                   "504/720;492/708",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "BO15/10",
                   "StromWE2012",
                   "intelectual disability",
                   "13:115090509",
                   "sub(C->T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "CHAMP1",
                   "",
                   "CHAMP1:nonsense",
                   "CHAMP1:nonsense",
                   "denovo",
                   "nonsense",
                   "398/813(Arg->End);398/813(Arg->End);398/813(Arg->End)",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "ER10924",
                   "StromWE2012",
                   "intelectual disability",
                   "15:72847668",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "ARIH1",
                   "",
                   "ARIH1:frame-shift",
                   "ARIH1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "215/558",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "MS134",
                   "StromWE2012",
                   "intelectual disability",
                   "15:93498742",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "CHD2",
                   "",
                   "CHD2:frame-shift",
                   "CHD2:frame-shift",
                   "denovo",
                   "frame-shift",
                   "603/1829",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "BO22/10",
                   "StromWE2012",
                   "intelectual disability",
                   "18:42531079",
                   "sub(A->T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "SETBP1",
                   "",
                   "SETBP1:nonsense",
                   "SETBP1:nonsense",
                   "denovo",
                   "nonsense",
                   "592/1597(Lys->End)",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "DD15743",
                   "StromWE2012",
                   "intelectual disability",
                   "X:41203492",
                   "del(1)",
                   "2 1 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "DDX3X",
                   "",
                   "DDX3X:frame-shift",
                   "DDX3X:frame-shift",
                   "denovo",
                   "frame-shift",
                   "289/663;289/662;273/647",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "E10-0275",
                   "StromWE2012",
                   "intelectual disability",
                   "X:53277315",
                   "sub(G->A)",
                   "2 1 0/0 0 1",
                   "",
                   "prbM",
                   "nonsense",
                   "IQSEC2",
                   "",
                   "IQSEC2:nonsense",
                   "IQSEC2:nonsense",
                   "denovo",
                   "nonsense",
                   "855/1489(Arg->End);650/950(Arg->End)",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "BO17/09",
                   "StromWE2012",
                   "intelectual disability",
                   "X:153296093",
                   "del(23)",
                   "2 1 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "MECP2",
                   "",
                   "MECP2:frame-shift",
                   "MECP2:frame-shift",
                   "denovo",
                   "frame-shift",
                   "400/499;388/487",
                   "",
                   "",
                   "",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio088",
                   "VissersWE2012",
                   "intelectual disability",
                   "1:35476591",
                   "del(2)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "ZMYM6",
                   "",
                   "ZMYM6:frame-shift",
                   "ZMYM6:frame-shift",
                   "denovo",
                   "frame-shift",
                   "370/1326",
                   "",
                   "",
                   "nan",
                   "0.01",
                   "0.0",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio093",
                   "VissersWE2012",
                   "intelectual disability",
                   "1:38322998",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "MTF1",
                   "",
                   "MTF1:frame-shift",
                   "MTF1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "111/754",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "Trio069",
                   "VissersWE2012",
                   "intelectual disability",
                   "1:153785737",
                   "sub(G->A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "GATAD2B",
                   "",
                   "GATAD2B:nonsense",
                   "GATAD2B:nonsense",
                   "denovo",
                   "nonsense",
                   "470/594(Gln->End)",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio092",
                   "VissersWE2012",
                   "intelectual disability",
                   "2:1891259",
                   "sub(C->T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "splice-site",
                   "MYT1L",
                   "",
                   "MYT1L:splice-site",
                   "MYT1L:splice-site",
                   "denovo",
                   "splice-site",
                   "879/1185",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio022",
                   "VissersWE2012",
                   "intelectual disability",
                   "2:166231415",
                   "sub(G->A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "SCN2A",
                   "",
                   "SCN2A:nonsense",
                   "SCN2A:nonsense",
                   "denovo",
                   "nonsense",
                   "1398/2006(Trp->End);1398/2006(Trp->End);1398/2006(Trp->End)",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio081",
                   "VissersWE2012",
                   "intelectual disability",
                   "2:170009333",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "frame-shift",
                   "LRP2",
                   "",
                   "LRP2:frame-shift",
                   "LRP2:frame-shift",
                   "denovo",
                   "frame-shift",
                   "4146/4656",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "Trio070",
                   "VissersWE2012",
                   "intelectual disability",
                   "3:41275106",
                   "del(4)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "CTNNB1",
                   "",
                   "CTNNB1:frame-shift",
                   "CTNNB1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "424/782;424/782;424/782",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio016",
                   "VissersWE2012",
                   "intelectual disability",
                   "6:33402928",
                   "sub(G->A)",
                   "2 2 1/0 0 1",
                   "",
                   "prbM",
                   "splice-site",
                   "SYNGAP1",
                   "",
                   "SYNGAP1:splice-site",
                   "SYNGAP1:splice-site",
                   "denovo",
                   "splice-site",
                   "170/1344",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbM",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityM"
                ],
                [
                   "Trio005",
                   "VissersWE2012",
                   "intelectual disability",
                   "6:79672902",
                   "sub(A->C)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "PHIP",
                   "",
                   "PHIP:nonsense",
                   "PHIP:nonsense",
                   "denovo",
                   "nonsense",
                   "1149/1822(Tyr->End)",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio022",
                   "VissersWE2012",
                   "intelectual disability",
                   "6:87966175",
                   "del(2)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "ZNF292",
                   "",
                   "ZNF292:frame-shift",
                   "ZNF292:frame-shift",
                   "denovo",
                   "frame-shift",
                   "943/2724",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio040",
                   "VissersWE2012",
                   "intelectual disability",
                   "10:28824551",
                   "sub(C->T)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "nonsense",
                   "WAC",
                   "",
                   "WAC:nonsense|WAC:non-coding",
                   "WAC:nonsense",
                   "denovo",
                   "nonsense",
                   "47/648(Arg->End);47/545(Arg->End)|5924",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio007",
                   "VissersWE2012",
                   "intelectual disability",
                   "12:49578808",
                   "del(1)",
                   "2 2 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "TUBA1A",
                   "",
                   "TUBA1A:frame-shift",
                   "TUBA1A:frame-shift",
                   "denovo",
                   "frame-shift",
                   "447/452;412/417;447/452",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ],
                [
                   "Trio059",
                   "VissersWE2012",
                   "intelectual disability",
                   "X:19369436",
                   "ins(GA)",
                   "2 1 1/0 0 1",
                   "",
                   "prbF",
                   "frame-shift",
                   "PDHA1",
                   "",
                   "PDHA1:frame-shift",
                   "PDHA1:frame-shift",
                   "denovo",
                   "frame-shift",
                   "110/391;110/360;117/398;148/429",
                   "",
                   "",
                   "nan",
                   "nan",
                   "nan",
                   "",
                   "NA:NA",
                   "prbF",
                   "NA",
                   "NA",
                   "",
                   [[{"level": 0, "gender": "F", "color": "#e35252", "label": null}, {"level": 0, "gender": "M", "color": "#bbbbbb", "label": "1"}], [{"level": 1, "gender": "M", "color": "#ffffff", "smallLabel": "1"}]],
                   "intelectual disabilityF"
                ]
             ],
             "cols":[
                "family id",
                "study",
                "study phenotype",
                "location",
                "variant",
                "family genotype",
                "from parent",
                "in child",
                "worst requested effect",
                "genes",
                "count",
                "all effects",
                "requested effects",
                "population type",
                "worst effect type",
                "effect details",
                "alternative allele frequency",
                "number of alternative alleles",
                "SSCfreq",
                "EVSfreq",
                "E65freq",
                "number of genotyped parents",
                "parent races",
                "children description",
                "proband verbal iq",
                "proband non-verbal iq",
                "validation status",
                "_pedigree_",
                "phenoInChS"
             ]
          }


### Get example gene weights [/gene_weights]

#### Get example gene weights  [GET]
Returns example gene weights
+ Response 200 (application/json)
  [
     {
        "bars":[
           124,
           126,
           123,
           121,
           121,
           101,
           132,
           116,
           133,
           160,
           93,
           117,
           125,
           121,
           131,
           138,
           153,
           25,
           165,
           155,
           58,
           155,
           191,
           59,
           176,
           68,
           30,
           233,
           96,
           196,
           48,
           96,
           233,
           56,
           82,
           208,
           66,
           133,
           13,
           239,
           88,
           183,
           12,
           238,
           117,
           111,
           147,
           25,
           260,
           21,
           136,
           147,
           62,
           157,
           5,
           245,
           72,
           173,
           47,
           205,
           4,
           276,
           55,
           149,
           135,
           169,
           62,
           17,
           237,
           75,
           168,
           118,
           70,
           182,
           122,
           23,
           278,
           92,
           28,
           181,
           124,
           129,
           72,
           168,
           109,
           27,
           249,
           146,
           67,
           145,
           177,
           62,
           128,
           131,
           115,
           189,
           17,
           136,
           92,
           172,
           127,
           114,
           208,
           71,
           121,
           47,
           162,
           121,
           147,
           117,
           124,
           111,
           129,
           175,
           77,
           123,
           114,
           108,
           113,
           150,
           108,
           120,
           124,
           117,
           120,
           120,
           160,
           114,
           85,
           150,
           121,
           124,
           108,
           138,
           123,
           107,
           135,
           139,
           109,
           127,
           114,
           124,
           127,
           123,
           122,
           123,
           121,
           123,
           144,
           167
        ],
        "weight":"LGD_rank",
        "min":0.0,
        "max":18400.0,
        "step":"1",
        "bins":[
           1.0,
           123.62333333333333,
           246.24666666666667,
           368.87,
           491.49333333333334,
           614.1166666666667,
           736.74,
           859.3633333333333,
           981.9866666666667,
           1104.6100000000001,
           1227.2333333333333,
           1349.8566666666666,
           1472.48,
           1595.1033333333335,
           1717.7266666666667,
           1840.35,
           1962.9733333333334,
           2085.596666666667,
           2208.2200000000003,
           2330.8433333333332,
           2453.4666666666667,
           2576.09,
           2698.713333333333,
           2821.3366666666666,
           2943.96,
           3066.5833333333335,
           3189.206666666667,
           3311.83,
           3434.4533333333334,
           3557.076666666667,
           3679.7,
           3802.3233333333333,
           3924.9466666666667,
           4047.57,
           4170.193333333334,
           4292.816666666667,
           4415.4400000000005,
           4538.0633333333335,
           4660.6866666666665,
           4783.31,
           4905.933333333333,
           5028.556666666666,
           5151.18,
           5273.803333333333,
           5396.426666666666,
           5519.05,
           5641.673333333333,
           5764.296666666667,
           5886.92,
           6009.543333333333,
           6132.166666666667,
           6254.79,
           6377.413333333334,
           6500.036666666667,
           6622.66,
           6745.283333333334,
           6867.906666666667,
           6990.53,
           7113.153333333334,
           7235.776666666667,
           7358.4,
           7481.0233333333335,
           7603.6466666666665,
           7726.27,
           7848.893333333333,
           7971.516666666666,
           8094.14,
           8216.763333333334,
           8339.386666666667,
           8462.01,
           8584.633333333333,
           8707.256666666666,
           8829.880000000001,
           8952.503333333334,
           9075.126666666667,
           9197.75,
           9320.373333333333,
           9442.996666666666,
           9565.62,
           9688.243333333334,
           9810.866666666667,
           9933.49,
           10056.113333333333,
           10178.736666666668,
           10301.36,
           10423.983333333334,
           10546.606666666667,
           10669.23,
           10791.853333333333,
           10914.476666666667,
           11037.1,
           11159.723333333333,
           11282.346666666666,
           11404.97,
           11527.593333333334,
           11650.216666666667,
           11772.84,
           11895.463333333333,
           12018.086666666666,
           12140.710000000001,
           12263.333333333334,
           12385.956666666667,
           12508.58,
           12631.203333333333,
           12753.826666666668,
           12876.45,
           12999.073333333334,
           13121.696666666667,
           13244.32,
           13366.943333333333,
           13489.566666666668,
           13612.19,
           13734.813333333334,
           13857.436666666666,
           13980.06,
           14102.683333333334,
           14225.306666666667,
           14347.93,
           14470.553333333333,
           14593.176666666666,
           14715.8,
           14838.423333333334,
           14961.046666666667,
           15083.67,
           15206.293333333333,
           15328.916666666666,
           15451.54,
           15574.163333333334,
           15696.786666666667,
           15819.41,
           15942.033333333333,
           16064.656666666668,
           16187.28,
           16309.903333333334,
           16432.52666666667,
           16555.15,
           16677.773333333334,
           16800.396666666667,
           16923.02,
           17045.643333333333,
           17168.266666666666,
           17290.89,
           17413.513333333332,
           17536.136666666665,
           17658.760000000002,
           17781.383333333335,
           17904.006666666668,
           18026.63,
           18149.253333333334,
           18271.876666666667,
           18394.5
        ],
        "desc":"LGD rank"
     },
     {
        "bars":[
           111,
           111,
           111,
           111,
           111,
           111,
           112,
           110,
           109,
           107,
           117,
           111,
           109,
           112,
           107,
           115,
           107,
           116,
           109,
           113,
           115,
           110,
           109,
           105,
           112,
           116,
           102,
           111,
           120,
           108,
           125,
           88,
           108,
           132,
           101,
           125,
           99,
           93,
           119,
           112,
           146,
           79,
           124,
           111,
           126,
           80,
           151,
           79,
           115,
           99,
           126,
           103,
           138,
           93,
           65,
           160,
           78,
           133,
           111,
           117,
           104,
           113,
           112,
           76,
           156,
           103,
           107,
           120,
           73,
           135,
           116,
           99,
           125,
           137,
           63,
           128,
           86,
           147,
           77,
           135,
           110,
           131,
           100,
           104,
           135,
           85,
           139,
           90,
           107,
           100,
           118,
           130,
           105,
           79,
           130,
           104,
           116,
           136,
           74,
           132,
           103,
           120,
           103,
           113,
           105,
           113,
           122,
           90,
           131,
           112,
           87,
           131,
           116,
           97,
           115,
           111,
           110,
           112,
           109,
           105,
           117,
           102,
           128,
           113,
           100,
           107,
           119,
           110,
           106,
           121,
           103,
           115,
           110,
           110,
           114,
           107,
           111,
           112,
           110,
           109,
           114,
           110,
           112,
           109,
           113,
           110,
           110,
           112,
           111,
           111
        ],
        "weight":"RVIS_rank",
        "min":0.0,
        "max":16640.0,
        "step":"1",
        "bins":[
           1.0,
           111.94,
           222.88,
           333.82,
           444.76,
           555.7,
           666.64,
           777.5799999999999,
           888.52,
           999.46,
           1110.4,
           1221.34,
           1332.28,
           1443.22,
           1554.1599999999999,
           1665.1,
           1776.04,
           1886.98,
           1997.92,
           2108.86,
           2219.8,
           2330.74,
           2441.68,
           2552.62,
           2663.56,
           2774.5,
           2885.44,
           2996.38,
           3107.3199999999997,
           3218.2599999999998,
           3329.2,
           3440.14,
           3551.08,
           3662.02,
           3772.96,
           3883.9,
           3994.84,
           4105.78,
           4216.72,
           4327.66,
           4438.6,
           4549.54,
           4660.48,
           4771.42,
           4882.36,
           4993.3,
           5104.24,
           5215.18,
           5326.12,
           5437.0599999999995,
           5548.0,
           5658.94,
           5769.88,
           5880.82,
           5991.76,
           6102.7,
           6213.639999999999,
           6324.58,
           6435.5199999999995,
           6546.46,
           6657.4,
           6768.34,
           6879.28,
           6990.22,
           7101.16,
           7212.099999999999,
           7323.04,
           7433.98,
           7544.92,
           7655.86,
           7766.8,
           7877.74,
           7988.68,
           8099.62,
           8210.56,
           8321.5,
           8432.44,
           8543.38,
           8654.32,
           8765.26,
           8876.2,
           8987.14,
           9098.08,
           9209.02,
           9319.96,
           9430.9,
           9541.84,
           9652.78,
           9763.72,
           9874.66,
           9985.6,
           10096.539999999999,
           10207.48,
           10318.42,
           10429.36,
           10540.3,
           10651.24,
           10762.18,
           10873.119999999999,
           10984.06,
           11095.0,
           11205.94,
           11316.88,
           11427.82,
           11538.76,
           11649.699999999999,
           11760.64,
           11871.58,
           11982.52,
           12093.46,
           12204.4,
           12315.34,
           12426.279999999999,
           12537.22,
           12648.16,
           12759.1,
           12870.039999999999,
           12980.98,
           13091.92,
           13202.86,
           13313.8,
           13424.74,
           13535.68,
           13646.619999999999,
           13757.56,
           13868.5,
           13979.44,
           14090.38,
           14201.32,
           14312.26,
           14423.199999999999,
           14534.14,
           14645.08,
           14756.02,
           14866.96,
           14977.9,
           15088.84,
           15199.779999999999,
           15310.72,
           15421.66,
           15532.6,
           15643.539999999999,
           15754.48,
           15865.42,
           15976.36,
           16087.3,
           16198.24,
           16309.18,
           16420.12,
           16531.06,
           16642.0
        ],
        "desc":"RVIS rank"
     },
     {
        "bars":[
           152,
           122,
           120,
           121,
           121,
           122,
           120,
           121,
           122,
           121,
           121,
           119,
           122,
           119,
           120,
           122,
           121,
           120,
           122,
           121,
           120,
           119,
           122,
           121,
           120,
           120,
           117,
           121,
           118,
           121,
           121,
           120,
           120,
           121,
           120,
           121,
           121,
           120,
           119,
           119,
           121,
           121,
           119,
           121,
           119,
           117,
           121,
           119,
           118,
           115,
           119,
           113,
           118,
           122,
           121,
           119,
           121,
           117,
           120,
           115,
           116,
           118,
           118,
           118,
           117,
           117,
           118,
           121,
           117,
           120,
           120,
           119,
           117,
           118,
           117,
           117,
           118,
           122,
           116,
           119,
           116,
           119,
           120,
           119,
           118,
           119,
           119,
           118,
           120,
           120,
           117,
           118,
           121,
           120,
           122,
           121,
           119,
           121,
           121,
           117,
           116,
           122,
           121,
           120,
           120,
           122,
           121,
           119,
           122,
           119,
           119,
           118,
           119,
           119,
           121,
           119,
           122,
           120,
           122,
           121,
           121,
           120,
           124,
           116,
           123,
           122,
           119,
           121,
           120,
           120,
           121,
           120,
           118,
           121,
           121,
           121,
           122,
           117,
           122,
           121,
           121,
           121,
           120,
           120,
           122,
           121,
           118,
           121,
           121,
           122
        ],
        "weight":"pLI_rank",
        "min":30.5,
        "max":18230.0,
        "step":"1",
        "bins":[
           31.5,
           152.79000000000002,
           274.08000000000004,
           395.37,
           516.6600000000001,
           637.95,
           759.24,
           880.5300000000001,
           1001.82,
           1123.1100000000001,
           1244.4,
           1365.69,
           1486.98,
           1608.27,
           1729.5600000000002,
           1850.8500000000001,
           1972.14,
           2093.4300000000003,
           2214.7200000000003,
           2336.01,
           2457.3,
           2578.59,
           2699.88,
           2821.17,
           2942.46,
           3063.75,
           3185.04,
           3306.3300000000004,
           3427.6200000000003,
           3548.9100000000003,
           3670.2000000000003,
           3791.4900000000002,
           3912.78,
           4034.07,
           4155.360000000001,
           4276.650000000001,
           4397.9400000000005,
           4519.2300000000005,
           4640.52,
           4761.81,
           4883.1,
           5004.39,
           5125.68,
           5246.97,
           5368.26,
           5489.55,
           5610.84,
           5732.13,
           5853.42,
           5974.71,
           6096.0,
           6217.29,
           6338.58,
           6459.87,
           6581.160000000001,
           6702.450000000001,
           6823.740000000001,
           6945.030000000001,
           7066.320000000001,
           7187.610000000001,
           7308.900000000001,
           7430.1900000000005,
           7551.4800000000005,
           7672.77,
           7794.06,
           7915.35,
           8036.64,
           8157.93,
           8279.220000000001,
           8400.51,
           8521.800000000001,
           8643.09,
           8764.380000000001,
           8885.67,
           9006.960000000001,
           9128.25,
           9249.54,
           9370.83,
           9492.12,
           9613.41,
           9734.7,
           9855.99,
           9977.28,
           10098.57,
           10219.86,
           10341.15,
           10462.44,
           10583.730000000001,
           10705.02,
           10826.310000000001,
           10947.6,
           11068.890000000001,
           11190.18,
           11311.470000000001,
           11432.76,
           11554.050000000001,
           11675.34,
           11796.630000000001,
           11917.92,
           12039.210000000001,
           12160.5,
           12281.79,
           12403.08,
           12524.37,
           12645.66,
           12766.95,
           12888.24,
           13009.53,
           13130.820000000002,
           13252.11,
           13373.400000000001,
           13494.69,
           13615.980000000001,
           13737.27,
           13858.560000000001,
           13979.85,
           14101.140000000001,
           14222.43,
           14343.720000000001,
           14465.01,
           14586.300000000001,
           14707.59,
           14828.880000000001,
           14950.17,
           15071.460000000001,
           15192.75,
           15314.04,
           15435.33,
           15556.62,
           15677.910000000002,
           15799.2,
           15920.490000000002,
           16041.78,
           16163.070000000002,
           16284.36,
           16405.65,
           16526.940000000002,
           16648.23,
           16769.52,
           16890.81,
           17012.100000000002,
           17133.39,
           17254.68,
           17375.97,
           17497.260000000002,
           17618.55,
           17739.84,
           17861.13,
           17982.420000000002,
           18103.71,
           18225.0
        ],
        "desc":"ExAC pLI rank"
     },
     {
        "bars":[
           127,
           121,
           122,
           121,
           121,
           120,
           122,
           118,
           121,
           120,
           121,
           118,
           120,
           121,
           121,
           121,
           120,
           122,
           119,
           121,
           121,
           122,
           121,
           120,
           119,
           120,
           122,
           120,
           120,
           120,
           122,
           120,
           120,
           120,
           122,
           120,
           120,
           119,
           120,
           122,
           120,
           121,
           118,
           122,
           119,
           121,
           120,
           122,
           120,
           119,
           120,
           120,
           117,
           121,
           122,
           118,
           121,
           121,
           121,
           118,
           121,
           115,
           115,
           120,
           118,
           117,
           115,
           117,
           117,
           120,
           114,
           118,
           117,
           120,
           119,
           121,
           122,
           113,
           112,
           119,
           118,
           117,
           117,
           118,
           120,
           119,
           120,
           120,
           119,
           121,
           120,
           120,
           116,
           122,
           120,
           118,
           118,
           122,
           121,
           120,
           120,
           121,
           121,
           119,
           121,
           120,
           121,
           120,
           122,
           119,
           121,
           121,
           120,
           119,
           119,
           120,
           120,
           121,
           121,
           119,
           119,
           120,
           120,
           120,
           120,
           121,
           121,
           121,
           122,
           121,
           122,
           120,
           121,
           120,
           120,
           120,
           120,
           121,
           121,
           122,
           121,
           122,
           120,
           121,
           121,
           122,
           121,
           121,
           121,
           122
        ],
        "weight":"pRec_rank",
        "min":5.0,
        "max":18230.0,
        "step":"1",
        "bins":[
           6.0,
           127.46,
           248.92,
           370.38,
           491.84,
           613.3,
           734.76,
           856.2199999999999,
           977.68,
           1099.1399999999999,
           1220.6,
           1342.06,
           1463.52,
           1584.98,
           1706.4399999999998,
           1827.8999999999999,
           1949.36,
           2070.8199999999997,
           2192.2799999999997,
           2313.74,
           2435.2,
           2556.66,
           2678.12,
           2799.58,
           2921.04,
           3042.5,
           3163.96,
           3285.4199999999996,
           3406.8799999999997,
           3528.3399999999997,
           3649.7999999999997,
           3771.2599999999998,
           3892.72,
           4014.18,
           4135.639999999999,
           4257.099999999999,
           4378.5599999999995,
           4500.0199999999995,
           4621.48,
           4742.94,
           4864.4,
           4985.86,
           5107.32,
           5228.78,
           5350.24,
           5471.7,
           5593.16,
           5714.62,
           5836.08,
           5957.54,
           6079.0,
           6200.46,
           6321.92,
           6443.38,
           6564.839999999999,
           6686.299999999999,
           6807.759999999999,
           6929.219999999999,
           7050.679999999999,
           7172.139999999999,
           7293.599999999999,
           7415.0599999999995,
           7536.5199999999995,
           7657.98,
           7779.44,
           7900.9,
           8022.36,
           8143.82,
           8265.279999999999,
           8386.74,
           8508.199999999999,
           8629.66,
           8751.119999999999,
           8872.58,
           8994.039999999999,
           9115.5,
           9236.96,
           9358.42,
           9479.88,
           9601.34,
           9722.8,
           9844.26,
           9965.72,
           10087.18,
           10208.64,
           10330.1,
           10451.56,
           10573.019999999999,
           10694.48,
           10815.939999999999,
           10937.4,
           11058.859999999999,
           11180.32,
           11301.779999999999,
           11423.24,
           11544.699999999999,
           11666.16,
           11787.619999999999,
           11909.08,
           12030.539999999999,
           12152.0,
           12273.46,
           12394.92,
           12516.38,
           12637.84,
           12759.3,
           12880.76,
           13002.22,
           13123.679999999998,
           13245.14,
           13366.599999999999,
           13488.06,
           13609.519999999999,
           13730.98,
           13852.439999999999,
           13973.9,
           14095.359999999999,
           14216.82,
           14338.279999999999,
           14459.74,
           14581.199999999999,
           14702.66,
           14824.119999999999,
           14945.58,
           15067.039999999999,
           15188.5,
           15309.96,
           15431.42,
           15552.88,
           15674.339999999998,
           15795.8,
           15917.259999999998,
           16038.72,
           16160.179999999998,
           16281.64,
           16403.1,
           16524.559999999998,
           16646.02,
           16767.48,
           16888.94,
           17010.399999999998,
           17131.86,
           17253.32,
           17374.78,
           17496.239999999998,
           17617.7,
           17739.16,
           17860.62,
           17982.079999999998,
           18103.54,
           18225.0
        ],
        "desc":"ExAC pRec rank"
     }
  ]

### Get Whole Genome data for Given Filters [/gene_weights/partition]

#### Get table data for given filters [POST]
Returns all effect types groups for givent dataset.
+ Request (application/json)
    + Body
          {}

+ Response 200 (application/json)
  {
     "right":{
        "count":5612,
        "percent":0.30402513678964194
     },
     "mid":{
        "count":10522,
        "percent":0.5700200444227748
     },
     "weights":"LGD_rank",
     "wmax":12841.0,
     "wmin":2327.0,
     "left":{
        "count":2325,
        "percent":0.1259548187875833
     }
  }


### Get Gene sets [/gene_sets]

#### Get Gene sets [GET]
Returns all gene sets
+ Response 200 (application/json)
    {
       "gene_sets":[
          {
             "conf":[
                "key",
                " (",
                "count",
                "): ",
                "desc"
             ],
             "val":"main",
             "label":"Main",
             "types": []
          },
          {
             "conf":[
                "key",
                " (",
                "count",
                ")"
             ],
             "val":"denovo",
             "label":"Denovo",
             "types": [{"color":"#e35252","id":"autism","name":"autism"},{"color":"#b8008a","id":"congenital heart disease","name":"congenital heart disease"},{"color":"#e3d252","id":"epilepsy","name":"epilepsy"},{"color":"#99d8e8","id":"intelectual disability","name":"intelectual disability"},{"color":"#98e352","id":"schizophrenia","name":"schizophrenia"},{"color":"#ffffff","id":"unaffected","name":"unaffected"},{"color":"#aaaaaa","id":"unknown","name":"unknown"}]
          },
          {
             "conf":[
                "key",
                " (",
                "count",
                ")"
             ],
             "val":"MSigDB.curated",
             "label":"MSigDB Pathways",
             "types": []
          },
          {
             "conf":[
                "key",
                " (",
                "count",
                "): ",
                "desc"
             ],
             "val":"GO",
             "label":"GO Terms",
             "types": []
          },
          {
             "conf":[
                "key",
                " (",
                "count",
                "): ",
                "desc"
             ],
             "val":"domain",
             "label":"Protein domains",
             "types": []
          },
          {
             "conf":[
                "key",
                " (",
                "count",
                ")"
             ],
             "val":"miRNA.Darnell",
             "label":"miRNA from Darnell",
             "types": []
          }
       ]
    }
### Get Gene sets [/gene_sets_list]

#### Get Gene sets [GET]
Returns all gene sets
+ Response 200 (application/json)
  [
     {
        "name": "topotecan downreg genes",
        "count":154,
        "desc":"King IF, et al. Topoisomerases facilitate transcription of long genes linked to autism. Nature (2013)"
     },
     {
        "name": "autism candidates from Iossifov PNAS 2015",
        "count":239,
        "desc":"Iossifov I., et al. Low load for disruptive mutations in autism genes and their biased transmission. PNAS (2015)"
     },
     {
        "name": "CHD8 target genes",
        "count":2158,
        "desc":"Cotney J, et al. The autism-associated chromatin modifier CHD8 regulates other autism risk genes during human neurodevelopment. Nat Commun. (2015)"
     },
     {
        "name": "postsynaptic inhibition",
        "count":181,
        "desc":"Akiyoshi Uezu, et al. Identification of an elaborate complex mediating postsynaptic inhibition. Science (2016)"
     },
     {
        "name": "PSD",
        "count":1445,
        "desc":"Bayes A., et al. Characterization of the proteome, diseases and evolution of the human postsynaptic density. Nature Neuroscience (2011)"
     },
     {
        "name": "essential genes",
        "count":2472,
        "desc":"Georgi B., et al. From mouse to human: evolutionary genomics analysis of human orthologs of essential genes. PLos Genetics (2013)"
     },
     {
        "name": "brain embryonically expressed",
        "count":1912,
        "desc":"Iossifov I., et al. The contribution of de novo coding mutations to autism spectrum disorder. Nature (2014)"
     },
     {
        "name": "chromatin modifiers",
        "count":428,
        "desc":"Iossifov I., et al. The contribution of de novo coding mutations to autism spectrum disorder. Nature (2014)"
     },
     {
        "name": "synaptic clefts inhibitory",
        "count":41,
        "desc":"Ken H. Loh, et al. Proteomic Analysis of Unbounded Cellular Compartments: Synaptic Clefts. Cell (2016)"
     },
     {
        "name": "synaptic clefts excitatory",
        "count":194,
        "desc":"Ken H. Loh, et al. Proteomic Analysis of Unbounded Cellular Compartments: Synaptic Clefts. Cell (2016)"
     },
     {
        "name": "non-essential genes",
        "count":3811,
        "desc":"Georgi B., et al. From mouse to human: evolutionary genomics analysis of human orthologs of essential genes. PLos Genetics (2013)"
     },
     {
        "name": "FMRP Tuschl",
        "count":939,
        "desc":"Ascano M., et al. FMRP targets distinct mRNA sequence elements to regulate protein expression. Nature (2012)"
     },
     {
        "name": "brain critical genes",
        "count":1744,
        "desc":"Uddin M, et al. Brain-expressed exons under purifying selection are enriched for de novo mutations in autism spectrum disorder. Nat Genetics (2014)"
     },
     {
        "name": "autism candidates from Sanders Neuron 2015",
        "count":65,
        "desc":"Sanders S., et. al, Insights into Autism Spectrum Disorder Genomic Architecture and Biology from 71 Risk Loci. Neuron (2015)"
     },
     {
        "name": "FMRP Darnell",
        "count":842,
        "desc":"Darnell JC., et al. FMRP stalls ribosomal translocation on mRNAs linked to synaptic function and autism. Cell (2011)"
     }
  ]
