---
- name: deploy seqpipe source
  hosts: all
  tasks:
    - name: delete old documentation directory
      file: path={{ doc_publish_dir }}/html state=absent

    - name: copy DAE html documentation
      synchronize: >
        src='gpf/DAE/docs/_build/html' 
        dest={{ doc_publish_dir }}/
        recursive=yes
