version: '3.7'
services:
  impala:

    image: seqpipe/seqpipe-docker-impala:latest    

  tests:
    image: ${DOCKER_IMAGE}
    
    volumes:
      - type: bind
        source: ${SOURCE_DIR}
        target: ${DOCKER_SOURCE_DIR}

      - type: bind
        source: ${DAE_DB_DIR}
        target: ${DOCKER_DAE_DB_DIR}

      - type: bind
        source: ${DAE_GENOMIC_SCORES_HG19}
        target: ${DOCKER_DAE_GENOMIC_SCORES_HG19}
      
      - type: bind
        source: ${DAE_GENOMIC_SCORES_HG38}
        target: ${DOCKER_DAE_GENOMIC_SCORES_HG38}

    env_file: scripts/test_env
    entrypoint: ["${DOCKER_SOURCE_DIR}/scripts/wait-for-it.sh", "impala:21050", 
      "--timeout=120", "--", 
      "tail -f /dev/null"]
      # "/code/jenkins_tests.sh"]
