# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - python=3.11
  - importlib_metadata=7.1
  - pysam=0.22.1
  - htslib=1.21
  - samtools=1.21
  - bcftools=1.21
  - pyliftover=0.4
  - pybigwig=0.3
  - lark-parser=0.6.7
  - networkx=2.8.5
  - numpy=2.2.1
  - scipy=1.15.0
  - pandas=2.2.3
  - pyarrow=19.0.1
  - scikit-learn=1.5
  - matplotlib-base=3.8
  - seaborn=0.13
  - fsspec=2024.12.0
  - s3fs=2024.12.0
  - dask=2024.12.1
  - dask-jobqueue=0.9.0
  - python-box=7.1
  - setuptools=70.3
  - sqlalchemy=2.0.21
  - sqlite=3.48.0
  - django=4.2.17
  - django-cors-headers=4.4
  - djangorestframework=3.15.2
  - django-oauth-toolkit=2.4
  - deprecation=2.1
  - toml=0.10
  - cerberus=1.3
  - jinja2=3.1.5
  - toolz=0.12
  - markdown2=2.4
  - python-duckdb=1.2.1
  - sqlglot=25
  - polars=1.14
  - sentry-sdk=2.12
  - pyzstd=0.16
  - gunicorn=22.0
  - mysqlclient=2.2
  - mysql-common=8.0
  - pydantic=2.8.2
  - requests=2.32.2
  - requests-oauthlib=2.0.0
  - versioneer=0.29
  - docker-py=7.1.0
  # pin the version of pyopenssl to pass the build
  - pyopenssl=24.2.1
