# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - bioconda
  - conda-forge
  - defaults
  - iossifovlab
dependencies:
  - python=3.9
  - importlib_metadata=4.11.3
  - pysam=0.19.0
  - samtools=1.15.1
  - htslib=1.15.1
  - bcftools=1.15.1
  - impyla=0.16.3
  - thriftpy2=0.4.14
  - thrift=0.13.0
  - lark-parser=0.6.7
  - networkx=2.7.1
  - numpy=1.22.3
  - scipy=1.7.3
  - scikit-learn=1.0.1
  - matplotlib-base=3.5.1
  - pandas=1.4.2
  - pyarrow=7.0.0
  - aiohttp=3.8.1
  - fsspec=2022.5.0
  - s3fs=2022.5.0
  - pyliftover=0.4
  - python-box=5.3.0
  - setuptools=52.0.0
  - sqlalchemy=1.4.27
  - sqlite=3.36.0
  - django=4.0.6
  - django-cors-headers=3.7.0
  - djangorestframework=3.12.4
  - openjdk=8.0.312
  - hadoop=3.1.2
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.4
  - jinja2=3.0.1
  - snakemake-minimal=6.12.1
  - ijson=3.1.4
  - dask=2022.1.0
  - dask-kubernetes=2022.1.0
  - tqdm=4.62.3
  - snakeobjects=3.0.7
  - google-cloud-bigquery=2.34.2
