# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - python=3.10
  - importlib_metadata=7.1
  - pysam=0.22
  - htslib=1.18
  - samtools=1.18
  - bcftools=1.18
  - pyliftover=0.4
  - lark-parser=0.6.7
  - networkx=2.8.5
  - numpy=1.26
  - scipy=1.10.0
  - scikit-learn=1.1.2
  - matplotlib-base=3.5.1
  - seaborn=0.13
  - pandas=2.1
  - pyarrow=16.1
  - snappy=1.1.10
  - fsspec=2024.5
  - s3fs=2024.5
  - dask=2024.5
  - python-box=7.1
  - setuptools=67
  - sqlalchemy=2.0.21
  - sqlite=3.45
  - django=4.2.11
  - django-cors-headers=4.0
  - djangorestframework=3.14
  - django-oauth-toolkit=2.2
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.4
  - jinja2=3.1.4
  - ijson=3.2
  - toolz=0.12.0
  - markdown2=2.4.0
  - python-duckdb=0.10.3
  - duckdb-engine=0.11.2
  - sqlglot=20.4
  - polars=0.20.18
  - sentry-sdk=1.18.0
  - pybigwig=0.3.22
