# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - python=3.12
  - pysam=0.23.3
  - htslib=1.22
  - samtools=1.22
  - bcftools=1.22
  - pyliftover=0.4.1
  - pybigwig=0.3.24
  - lark=1.2.2
  - filelock=3.19
  - networkx=2.8.5
  - numpy=2.2.6
  - scipy=1.15.2
  - pandas=2.2.3
  - pyarrow>=18
  - scikit-learn=1.5
  - matplotlib-base=3.8
  - seaborn=0.13
  - fsspec=2025.3.0
  - s3fs=2025.3.0
  - dask=2025.10
  - dask-jobqueue=0.9.0
  - jupyter-server-proxy=4.4.0
  - python-box=7.1
  - setuptools=70.3
  - pip=24.1
  - sqlite=3.48.0
  - django=5.2.5
  - django-cors-headers=4.7.0
  - djangorestframework=3.16.1
  - django-oauth-toolkit=3.0.1
  - deprecation=2.1
  - toml=0.10
  - cerberus=1.3
  - jinja2=3.1.5
  - toolz=0.12
  - markdown2=2.4
  - python-duckdb=1.4.1
  - sqlglot=25
  - polars=1.14
  - sentry-sdk=2.12
  - pyzstd=0.16
  - gunicorn=22.0
  - mysqlclient=2.2
  - mysql-common=8.0
  - pydantic=2.8.2
  - requests=2.32.2
  - requests-oauthlib=2.0.0
  - versioneer=0.29
  - docker-py=7.1.0
  # pin the version of pyopenssl to pass the build
  - pyopenssl=24.2.1
  # pin the version of importlib_metadata due to issues with dask
  - importlib_metadata=8.6.1
  - psutil
  - intervaltree
