# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - bioconda
  - conda-forge
  - defaults
  - iossifovlab
dependencies:
  - python=3.9.12
  - importlib_metadata=4.11.3
  - pysam=0.19.1
  - samtools=1.15.1
  - htslib=1.15.1
  - impyla=0.17.0
  - thriftpy2=0.4.14
  - thrift=0.16.0
  - lark-parser=0.6.7
  - networkx=2.8.5
  - numpy=1.23.1
  - scipy=1.9.0
  - scikit-learn=1.1.2
  - matplotlib-base=3.5.1
  - pandas=1.4.3
  - pyarrow=8.0.1
  - aiohttp=3.8.1
  - fsspec=2022.7.1
  - s3fs=2022.7.1
  - pyliftover=0.4
  - python-box=6.0.2
  - setuptools=65.0.1
  - sqlalchemy=1.4.40
  - sqlite=3.39.2
  - django=4.1.3
  - django-cors-headers=3.13.0
  - djangorestframework=3.13.1
  - django-oauth-toolkit=2.2.0
  - openjdk=8.0.312
  - hadoop=3.1.2
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.4
  - jinja2=3.1.2
  - snakemake-minimal=7.18.2
  - ijson=3.1.4
  - dask=2022.7.1
  - dask-kubernetes=2022.7.0
  - tqdm=4.64.0
  - markdown2=2.4.0
