# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
channels:
  - defaults
  - conda-forge 
  - bioconda
  - iossifovlab
dependencies:
  - pysam=0.16.0.1
  - samtools=1.12
  - impyla=0.16.3
  - thriftpy2=0.4.11
  - thrift=0.13.0
  - lark-parser=0.6.7
  - matplotlib=3.3.1
  - networkx=2.5.1
  - numpy=1.16.4
  - pandas=1.0.3
  - pyarrow=2.0.0
  - pyliftover=0.4
  - python=3.8
  - python-box=5.3.0
  - scipy=1.6.2
  - setuptools=52.0.0
  - sqlalchemy=1.4.19
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - django=2.2.8
  - django-cors-headers=3.2.1
  - django-guardian=2.4.0
  - djangorestframework=3.12.4
  - seaborn=0.11.1
  - openjdk=8.0.192
  - hadoop=3.1.2
  - pybigwig=0.3.18
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.2
  - jinja2=3.0.1
  - snakemake-minimal=6.5.2
  - ijson=3.1.3
  - lxml=4.6.3
