# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - defaults
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - python=3.9
  - importlib_metadata=4.11.3
  - pysam=0.20.0
  - samtools=1.15.1
  - htslib=1.15.1
  - pyliftover=0.4
  - lark-parser=0.6.7
  - networkx=2.8.5
  - numpy=1.23.1
  - scipy=1.9.0
  - scikit-learn=1.1.2
  - matplotlib-base=3.5.1
  - seaborn=0.12.1
  - pandas=1.5.2
  - pyarrow=10.0.1
  - fsspec=2023.3
  - aiohttp=3.8.4
  - python-box=6.0.2
  - setuptools=67
  - sqlalchemy=1.4.40
  - sqlite=3.40.1
  - django=4.2
  - django-cors-headers=4.0
  - djangorestframework=3.14
  - django-oauth-toolkit=2.2
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.4
  - jinja2=3.1.2
  - snakemake-minimal=7.24
  - ijson=3.1.4
  - s3fs=2023.3
  - openjdk=8.0.312
  - hadoop=3.1.2
  - impyla=0.17.0
  - thriftpy2=0.4.14
  - thrift=0.16.0
  - dask=2023.3
  - toolz=0.12.0
  - markdown2=2.4.0
  - python-duckdb=0.7.1
  - sentry-sdk=1.18.0