"""
This type stub file was generated by pyright.
"""

from cerberus.platform import importlib_metadata
from cerberus.schema import SchemaError, rules_set_registry, schema_registry
from cerberus.utils import TypeDefinition
from cerberus.validator import DocumentError, Validator as Validator

"""
    Extensible validation for Python dictionaries.

    :copyright: 2012-2023 by Nicola Iarocci.
    :license: ISC, see LICENSE for more details.

    Full documentation is available at https://python-cerberus.org/

"""
__version__ = ...
__all__ = [DocumentError.__name__, SchemaError.__name__, TypeDefinition.__name__, Validator.__name__, "schema_registry", "rules_set_registry", "__version__"]
