"""
This type stub file was generated by pyright.
"""

import sys
from collections.abc import (
    Callable,
    Container,
    Hashable,
    Iterable,
    Mapping,
    MutableMapping,
    Sequence,
    Set,
    Sized,
)

""" Platform-dependent objects """
if sys.flags.optimize == 2:
    ...
if sys.version_info < (3, ):
    ...
else:
    _int_types = ...
    _str_type = str
if sys.version_info < (3, 3):
    ...
if sys.version_info < (3, 8):
    ...
__all__ = ("_int_types", "_str_type", "importlib_metadata", Callable.__name__, Container.__name__, Hashable.__name__, Iterable.__name__, Mapping.__name__, MutableMapping.__name__, Sequence.__name__, Set.__name__, Sized.__name__)
