# Generated by Django 4.2.15 on 2024-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_state_save', '0002_auto_20190205_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='querystate',
            name='origin',
            field=models.CharField(blank=True, choices=[('saved', 'saved'), ('user', 'user'), ('system', 'system')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='querystate',
            name='timestamp',
            field=models.DateField(default=None, null=True),
        ),
    ]
