# Generated by Django 4.2.15 on 2024-11-21 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_state_save', '0002_auto_20190205_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='querystate',
            name='origin',
            field=models.CharField(
                choices=[
                    ('saved', 'saved'),
                    ('user', 'user'),
                    ('system', 'system')
                ],
                default='system',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='querystate',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
