
all:

test:
	nosetests
cover:
	nosetests --with-coverage --cover-html --cover-package DAE,VariantsDB,phenoDB,GeneInfoDB,GeneModelFiles,GeneTerms,GenomeAccess,GenomeDB,phenoDBUtils,query_variants,RegionOperations,SfariExportLoader,Sfari,SfariVariable,SfariVariableTracker,VariantAnnotation
