# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 12:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationpath",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="wdaeuser",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
