# Generated by Django 2.2.8 on 2021-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_auto_20190424_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
                ('failed_attempt', models.IntegerField()),
            ],
            options={
                'db_table': 'authentication_log',
            },
        ),
    ]
