# Generated by Django 4.0.4 on 2022-05-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_authenticationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdaeuser',
            name='date_joined',
        ),
    ]
