services:
  remote:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "21010:21010"
    environment:
      DAE_DB_DIR: /wd/federation/tmp/gpf_instance
    volumes:
      - ../:/wd
    entrypoint: /wd/federation/testing_entrypoint.sh
