services:
  remote:
    build:
      context: ../
    platform: linux/amd64
    ports:
      - "21010:21010"
    environment:
      DAE_DB_DIR: /wd/federation/tmp/instance
      GRR_DEFINITION_FILE: /wd/federation/tmp/grr_definiton.yaml
    volumes:
      - ../:/wd
    entrypoint: /wd/federation/testing_entrypoint.sh
