version: "3.9"
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range

  remote:
    build:
      context: ../
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "21010:21010"
    environment:
      DAE_DB_DIR: /wd/data/data-hg19-remote
      GRR_DEFINITION_FILE: /wd/integration/grr_definition.yaml
    volumes:
      - ../:/wd
    entrypoint: /wd/integration/remote/entrypoint.sh
