version: "3.9"
services:

  setup:
    build:
      context: ../
      dockerfile: ../Dockerfile
    platform: linux/amd64
    restart: "no"
    volumes:
      - ../:/wd
    entrypoint: /wd/rest_client/integration/setup.sh

  resttest:
    build:
      context: ../
      dockerfile: ../Dockerfile
    platform: linux/amd64
    depends_on:
      - setup
    ports:
      - "21011:21011"
    environment:
      DAE_DB_DIR: /wd/data/data-hg19-resttest
      GRR_DEFINITION_FILE: /wd/integration/grr_definition.yaml
    volumes:
      - ../:/wd
    entrypoint: /wd/rest_client/integration/entrypoint.sh
