FROM --platform=linux/amd64 condaforge/mambaforge:latest


ADD environment.yml /
ADD dev-environment.yml /
ADD rest_client/environment.yml /rest-environment.yml

RUN /opt/conda/bin/mamba update -n base -c conda-forge conda 
RUN /opt/conda/bin/mamba env create --name gpf --file /environment.yml
RUN /opt/conda/bin/mamba env update --name gpf --file /dev-environment.yml
RUN /opt/conda/bin/mamba env update --name gpf --file /rest-environment.yml

SHELL ["/bin/bash", "-c"]
