services:

  setup:
    extends:
      file: docker-compose-jenkins.yaml
      service: setup

  mail:
    extends:
      file: docker-compose-jenkins.yaml
      service: mail
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    extends:
      file: docker-compose-jenkins.yaml
      service: backend
    ports:
      - "21011:21011"
