version: "3.9"
services:

  setup:
    build:
      context: ../
      dockerfile: ../Dockerfile
    platform: linux/amd64
    restart: "no"
    volumes:
      - ../:/wd
    entrypoint: /wd/rest_client/integration/setup.sh

  mail:
    image: mailhog/mailhog
    hostname: mail
    ports:
      - "1025:1025"
      - "8025:8025"

  resttest:
    build:
      context: ../
      dockerfile: ../Dockerfile
    platform: linux/amd64
    depends_on:
      - setup
    ports:
      - "21011:21011"
    environment:
      DAE_DB_DIR: /wd/data/data-hg19-resttest
      GRR_DEFINITION_FILE: /wd/integration/grr_definition.yaml
      WDAE_ALLOWED_HOST: "*"
      WDAE_DEBUG: true
      WDAE_PUBLIC_HOSTNAME: resttest
      WDAE_EMAIL_HOST: "mail"
      WDAE_EMAIL_VERIFICATION_ENDPOINT: "http://resttest:21011"
    volumes:
      - ../:/wd
    entrypoint: /wd/rest_client/integration/entrypoint.sh
