# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 13:36
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_state_save', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querystate',
            name='page',
            field=models.CharField(choices=[('genotype', 'Genotype browser'), ('phenotype', 'Phenotype browser'), ('enrichment', 'Enrichment tool'), ('phenotool', 'Phenotype tool')], max_length=10),
        ),
    ]
