FROM federation-backend

COPY gpf_federation/federation-environment.yml /federation-environment.yml
COPY gpf_rest_client/rest-environment.yml /rest-environment.yml

RUN /opt/conda/bin/mamba env update --name gpf --file /rest-environment.yml
RUN /opt/conda/bin/mamba env update --name gpf --file /federation-environment.yml

