export const REGIONS_BLOCK_TAB_DESELECT = 'REGIONS_BLOCK_TAB_DESELECT';
export const GENES_BLOCK_TAB_DESELECT = 'GENES_BLOCK_TAB_DESELECT';
export const ENRICHMENT_MODELS_TAB_DESELECT = 'ENRICHMENT_MODELS_TAB_DESELECT';
