try:  # noqa: RUF067 — hatch-vcs version fallback
    from ._version import __version__
except ImportError:
    # _version.py is generated by hatch-vcs into the built wheel. It may be
    # absent when gpf-web is installed editable from a source checkout
    # (e.g. inside CI Docker images that don't ship .git).
    __version__ = "0.0.0.dev0"
