# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
name: gsd_dev
channels:
  - defaults
  - conda-forge 
  - bioconda
  - iossifovlab
dependencies:
  - pysam=0.16.0.1
  - samtools=1.12
  - impyla=0.16.3
  - thriftpy2=0.4.11
  - thrift=0.13.0
  - lark-parser=0.6.7
  - networkx=2.6.2
  - numpy=1.21.1
  - scipy=1.7.1
  - matplotlib=3.4.2
  - pandas=1.3.1
  - pyarrow=4.0.1
  - seaborn=0.11.1
  - statsmodels=0.12.2
  - pyliftover=0.4
  - python=3.8
  - python-box=5.3.0
  - setuptools=52.0.0
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - django=3.2.6
  - django-cors-headers=3.7.0
  - django-guardian=2.4.0
  - djangorestframework=3.12.4
  - openjdk=8.0.192
  - pybigwig=0.3.18
  - deprecation=2.1.0
  - toml=0.10.2
  - cerberus=1.3.2
  - jinja2=3.0.1
  - snakemake-minimal=6.5.2
  - ijson=3.1.4
  - lxml=4.6.3
  - beautifulsoup4=4.9.3
  - bump2version=1.0.1
  - pytest-doctestplus=0.4.0
  - sphinx=4.1.2
  - sphinx_rtd_theme=0.5.2
  - sphinx-copybutton=0.4.0
  - sphinxcontrib-httpdomain=1.7.0
  - coverage=5.5
  - flake8=3.9.2
  - mypy=0.910
  - pytest=6.2.4
  - pytest-cov=2.12.1
  - pytest-mock=3.6.1
  - pytest-xdist=2.3.0
  - pytest-django=4.4.0
  - pylint=2.9.1
  - pre-commit=2.13.0
  - django-extensions=2.2.5
  - autopep8
  - ipython
