# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
# - conda-forge 

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - numpy=1.26
  - pybigwig=0.3.22
  - snakemake-minimal=7.32
  - openjdk=8.0.312
  - hadoop=3.1.2
  - impyla=0.19.0
